[project]
name = "rerun_cpp_example_ros"
authors = ["rerun.io <opensource@rerun.io>"]
channels = ["robostack-staging", "conda-forge"]
description = "Use the Rerun C++ SDK together with ROS"
homepage = "https://rerun.io"
license = "Apache-2.0"
platforms = ["linux-64"]
repository = "https://github.com/rerun-io/cpp-example-ros"
version = "0.1.0"

[tasks]
ws = { cmd = "mkdir -p noetic_ws/src", cwd = "." }
build = { cmd = "mkdir src && catkin build --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON", depends_on = [ "ws"], cwd = "noetic_ws"}
example_data = { cmd = "curl -L -C - -O http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_forward_3_snapdragon_with_gt.bag", cwd = "noetic_ws"}
example = { cmd = "bash -c 'source ./devel/setup.bash && roslaunch rerun_logger example.launch'", depends_on = [ "build", "example_data"], cwd = "noetic_ws" }

[dependencies]
ros-noetic-desktop = ">=1.5.0,<1.6"
compilers = ">=1.7.0,<1.8"
opencv = ">=4.9.0,<4.10"
yaml-cpp = ">=0.8.0,<0.9"
ros-noetic-ros-type-introspection = ">=2.1.0,<2.2"
